### ISSUE TITLE
[BUG] The given key '1' was not present in the dictionary.

### ISSUE THREAD

**Issue by crashzk** [Cruze03/CS2-SimpleAdmin#1]
```
2024-11-01 21:25:47.195 -03:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key '1' was not present in the dictionary.
   at CS2_SimpleAdmin.CS2_SimpleAdmin.OnPlayerDeath(EventPlayerDeath event, GameEventInfo info) in /home/runner/work/CS2-SimpleAdmin/CS2-SimpleAdmin/CS2-SimpleAdmin/Events.cs:line 345
   at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
2024-11-01 21:25:47.223 -03:00 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: The given key '1' was not present in the dictionary.
   at CS2_SimpleAdmin.CS2_SimpleAdmin.OnPlayerDeath(EventPlayerDeath event, GameEventInfo info) in /home/runner/work/CS2-SimpleAdmin/CS2-SimpleAdmin/CS2-SimpleAdmin/Events.cs:line 345
   at InvokeStub_GameEventHandler`1.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```

**Comment by Cruze03** [comment]
Weird how it throws error. Usually `Dictionary.Remove` should do nothing if key doesn't exist in dictionary. Will update in next update

**Comment by Cruze03** [comment]
Can you try latest and confirm whether this issue still comes?

**Comment by crashzk** [comment]
I tested it here and apparently no errors at the moment... I'll be marking it as resolved, if anything I'll open the issues again. Thanks!
